# Generated by Django 4.2.7 on 2024-01-08 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlovha', models.CharField(help_text='Bu yerga maqola sarlovhasini kiriting:', max_length=250)),
                ('tanasi', models.TextField(help_text='maqolani matni:')),
                ('vaqt', models.DateTimeField(default=datetime.datetime(2024, 1, 8, 15, 15, 41, 78158), help_text='maqola matni')),
                ('rasm', models.ImageField(blank=True, help_text='Maqola uchun rasm', null=True, upload_to='blog_rasimlar/')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
    ]
