# Generated by Django 4.2.7 on 2024-01-08 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 15, 16, 4, 123701), help_text='maqola matni'),
        ),
    ]
